use_frameworks!

platform :ios, '8.0'

target 'ZZMedia_Example' do
  pod 'ZZMedia', :path => '../'
  pod 'OpenCV', '~>3.0.0'
  pod 'TesseractOCRiOS', '4.0.0'

  target 'ZZMedia_Tests' do
    inherit! :search_paths

    
  end
end
